
name: mybuild

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: ["opensuse/leap:15.3"]
#        os: ["opensuse/tumbleweed"]
#        include:
#          - os: "opensuse/leap:15.3"

    container:
      image: ${{ matrix.os }}

    steps:
      - name: prep
        run: |
          zypper -n --gpg-auto-import-keys ar https://download.opensuse.org/repositories/home:munix9/openSUSE_Leap_15.3/home:munix9.repo
          zypper -n --gpg-auto-import-keys ar https://download.opensuse.org/repositories/home:munix9:unstable/openSUSE_Leap_15.3/home:munix9:unstable.repo
          zypper -n ref && zypper -n up
          zypper -n in avif-tools 'celestia-tools>= 1.7.0~' cmake

      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: build & install
        run: |
          mkdir build install && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON ..
          make -O VERBOSE=1 -j && {
            echo -e "\n### make install ###\n"
            make install DESTDIR=../install
          }

      - name: convert
        run: |
          echo "convert"

#      - name: upload package_source
#        uses: actions/upload-artifact@v2
#        if: ${{ success() }}
#        with:
#          name: package_source
#          path: ${{ github.workspace }}/build/android-tools-*.tar.xz
